User.create!([
  {email: "tim@tim.com", encrypted_password: "$2a$10$KipzvyYiHq8mNF7C6qh/1uEovNhDFXhMCLmIXZofNhKnkvm1/NA8q", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 10, current_sign_in_at: "2016-01-28 00:23:37", last_sign_in_at: "2016-01-28 00:22:21", current_sign_in_ip: "::1", last_sign_in_ip: "::1"},
  {email: "a@b.com", encrypted_password: "$2a$10$zCES8jbZ5LjafZr5TbKBAufVMDpDXFnCAcxIhJpixRNfYrWLpBZ0e", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-01-27 03:03:44", last_sign_in_at: "2016-01-27 03:03:44", current_sign_in_ip: "::1", last_sign_in_ip: "::1"},
  {email: "123@123.com", encrypted_password: "$2a$10$dTi81kTbMy.xGlCK/VKFd.uot2fhHQNNKy1ZhJ0tKQaUZDF9NaKHK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-01-27 03:15:06", last_sign_in_at: "2016-01-27 03:15:06", current_sign_in_ip: "::1", last_sign_in_ip: "::1"},
  {email: "qwerty123@aol.com", encrypted_password: "$2a$10$JSDVf84eI7y5elYjLG8BnO7c/dITeXJnhxkGZOoE0YijnJTdTpqye", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2016-01-31 19:21:04", last_sign_in_at: "2016-01-28 02:23:46", current_sign_in_ip: "::1", last_sign_in_ip: "::1"},
  {email: "superman@aol.com", encrypted_password: "$2a$10$RkH510hFrFyAL3CVOxdrquu6ePFkzTqsfitbQVEMXnm9mgeSa3hPO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-01-28 00:25:52", last_sign_in_at: "2016-01-28 00:25:52", current_sign_in_ip: "::1", last_sign_in_ip: "::1"}
])
CategorizedProduct.create!([
  {product_id: 1, category_id: 1},
  {product_id: 1, category_id: 2},
  {product_id: 1, category_id: 8},
  {product_id: 2, category_id: 5},
  {product_id: 2, category_id: 9},
  {product_id: 3, category_id: 4},
  {product_id: 3, category_id: 9},
  {product_id: 4, category_id: 1},
  {product_id: 4, category_id: 8},
  {product_id: 5, category_id: 1},
  {product_id: 5, category_id: 2},
  {product_id: 5, category_id: 3},
  {product_id: 5, category_id: 8},
  {product_id: 6, category_id: 4},
  {product_id: 6, category_id: 9},
  {product_id: 7, category_id: 3},
  {product_id: 7, category_id: 6},
  {product_id: 7, category_id: 8},
  {product_id: 8, category_id: 4},
  {product_id: 8, category_id: 8},
  {product_id: 9, category_id: 7},
  {product_id: 10, category_id: 5},
  {product_id: 10, category_id: 9},
  {product_id: 11, category_id: 1},
  {product_id: 11, category_id: 6},
  {product_id: 11, category_id: 8},
  {product_id: 12, category_id: 4},
  {product_id: 12, category_id: 8},
  {product_id: 13, category_id: 5},
  {product_id: 13, category_id: 8},
  {product_id: 14, category_id: 2},
  {product_id: 14, category_id: 9},
  {product_id: 4, category_id: 6}
])
Category.create!([
  {name: "Red"},
  {name: "Green"},
  {name: "Purple"},
  {name: "Yellow"},
  {name: "Orange"},
  {name: "Berries"},
  {name: "Wine"},
  {name: "Okay To Eat The Outside Layer"},
  {name: "Don't Eat The Outside Layer"}
])
Image.create!([
  {url: "http://louisianalawblog.wp.lexblogs.com/wp-content/uploads/sites/342/2015/02/app.jpg", product_id: 1},
  {url: "http://realfood.tesco.com/media/images/Orange-and-almond-srping-cake-hero-58d07750-0952-47eb-bc41-a1ef9b81c01a-0-472x310.jpg", product_id: 2},
  {url: "http://images.all-free-download.com/images/graphicthumb/banana_310735.jpg", product_id: 3},
  {url: "https://heartuniverseorg.files.wordpress.com/2015/09/strawberry11.jpg", product_id: 4},
  {url: "http://www.lgssales.com/wp-content/uploads/comm_grapes.jpg", product_id: 5},
  {url: "http://freenology.com/images/71442946288pineapple.jpg", product_id: 6},
  {url: "http://venroyblueberries.com/assets/components/vrbbcust/images/blueberries.jpg", product_id: 7},
  {url: "http://www.naturespride.eu/uploads/tx_npdata/Starfruit_02.jpg", product_id: 8},
  {url: "http://www.winesfromspainusa.com/sites/default/files/WineFinder_Key%20Image-1.jpg?1322751759", product_id: 9},
  {url: "http://media.mercola.com/assets/images/food-facts/papaya-nutrition-facts.jpg", product_id: 10},
  {url: "http://www.naturipefarms.com/wp-content/uploads/2012/04/Raspberry-Image2.png", product_id: 11},
  {url: "http://www.freshtexproduce.com/products/mango-lg2.jpg", product_id: 12},
  {url: "http://freshmadisonmarket.com/sites/madison/files/uploads/blog/2015/08/MI-Peaches.jpg", product_id: 13},
  {url: "http://41.media.tumblr.com/tumblr_m4abln1YPn1qzecyno1_500.jpg", product_id: 14},
  {url: nil, product_id: 14}
])
Order.create!([
  {user_id: nil, product_id: nil, quantity: 2, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 2, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 2, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 2, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 2, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 2, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 2, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 4, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 3, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 3, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 3, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 3, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 3, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 3, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 3, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 3, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 80, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: nil, quantity: 800, subtotal: nil, tax: nil, total: nil},
  {user_id: nil, product_id: 6, quantity: 6, subtotal: nil, tax: nil, total: nil},
  {user_id: 4, product_id: 6, quantity: 10, subtotal: nil, tax: nil, total: nil},
  {user_id: 4, product_id: 9, quantity: 10, subtotal: nil, tax: nil, total: nil},
  {user_id: 4, product_id: 1, quantity: 5, subtotal: nil, tax: nil, total: nil},
  {user_id: 4, product_id: 13, quantity: 1, subtotal: nil, tax: nil, total: nil},
  {user_id: 4, product_id: 10, quantity: 5, subtotal: "250.0", tax: "22.5", total: "272.5"},
  {user_id: 4, product_id: 1, quantity: 5, subtotal: "12.5", tax: "1.13", total: "13.63"}
])
Product.create!([
  {name: "Apple", price: "2.5", description: "Round and delicious, comes in Red or Green", sales_tax: nil, supplier_id: 1},
  {name: "Orange", price: "1.25", description: "Citrus, full of Vitamin C. Only comes in Orange at this time.", sales_tax: nil, supplier_id: 2},
  {name: "Banana", price: "1.5", description: "Yellow!  Monkey approved!", sales_tax: nil, supplier_id: 3},
  {name: "Strawberry", price: "2.75", description: "Bite size. Red and delicious. Try dipped in chocolate", sales_tax: nil, supplier_id: 4},
  {name: "Grapes", price: "1.75", description: "A great snack. Comes in green, red, or purple. It's like edible non-alcoholic wine.", sales_tax: nil, supplier_id: 4},
  {name: "Pineapple", price: "2.0", description: "Tropical. Spikey on the outside, delicous on the inside.", sales_tax: nil, supplier_id: 3},
  {name: "Blueberries", price: "2.25", description: "Bite size snack. Note: product will not actually be blue", sales_tax: nil, supplier_id: 2},
  {name: "Star fruit", price: "4.0", description: "Pretty cool looking, right?", sales_tax: nil, supplier_id: 1},
  {name: "Better \"Grapes\"", price: "10.0", description: "So much better", sales_tax: nil, supplier_id: 1},
  {name: "Papaya", price: "50.0", description: "It's fun to say! Now 50% off", sales_tax: nil, supplier_id: 2},
  {name: "Raspberries", price: "2.0", description: "", sales_tax: nil, supplier_id: 3},
  {name: "Mango", price: "5.0", description: "Great in smoothies", sales_tax: nil, supplier_id: 4},
  {name: "Peaches", price: "2.5", description: "We have millions of peaches for you", sales_tax: nil, supplier_id: 2},
  {name: "Lime", price: "0.95", description: "Put the lime in the coconut", sales_tax: nil, supplier_id: 2}
])
Supplier.create!([
  {name: "John's Fresh Produce", email: "john@fresh.com", phone: "773-555-FRSH"},
  {name: "Kevin's Family Farm", email: "Kevin@farm.com", phone: "312-555-FARM"},
  {name: "Chris' Discount Produce", email: "chris@cheap.com", phone: "708-555-SALE"},
  {name: "Craig's Door To Door Produce", email: "craig@produce.com", phone: "708-555-DOOR"}
])
